language: scala
branches:
  only:
  - master
before_install:
- curl --silent https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz | tar xz -C
  /tmp/
- git clone https://github.com/ryanbrainard/heroku-buildpack-testrunner.git /tmp/testrunner
- "./etc/hatchet_travis_setup.sh"
install: true
script: eval "$TEST_CMD"
after_script: heroku keys:remove $USER@`hostname`
env:
  global:
  - IS_RUNNING_ON_TRAVIS=true
  - HATCHET_RETRIES=3
  - HATCHET_DEPLOY_STRATEGY=git
  - HATCHET_BUILDPACK_BASE="https://github.com/heroku/heroku-buildpack-scala.git"
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  - secure: nje0y5I8CYZK9qTzx4OHZZe/B2T4p3j9ehP9YiWGds+YmnUUAH5dGtMSzYlafamnb7aJ/Cn8G1kWCUWjeIb23zbiQFLwOwYNceo01Mvc4FL8rBBQDvpp2Ns/i0JL/1dVwF3uGtsFqeQLtMZlA5uYi50Bs+dvIr88t8RZnxEi6+M=
  matrix:
  - TEST_CMD='[ "$TRAVIS_PULL_REQUEST" = "false" ] && sbt hatchet || true'
  - TEST_CMD="/tmp/testrunner/bin/run -c ."
