language: scala
branches:
  only:
  - master
before_install:
- curl --silent https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz | tar xz -C
  /tmp/
- git clone https://github.com/heroku/heroku-buildpack-testrunner.git /tmp/testrunner
- "./etc/hatchet_travis_setup.sh"
install: true
script: eval "$TEST_CMD"
after_script: heroku keys:remove $USER@`hostname`
env:
  global:
  - IS_RUNNING_ON_TRAVIS=true
  - HATCHET_RETRIES=3
  - HATCHET_DEPLOY_STRATEGY=git
  - HATCHET_BUILDPACK_BASE="https://github.com/heroku/heroku-buildpack-scala.git"
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  - secure: A+pX0ddg61NSgxIE+gOgacmH9w4gIfilSIAy3Hw9cGKi7X+FeACPNhqPHlXpWNbnpS7aZnXw5B13GK0Nf8ol2IOJUj4wOJreI5f+5r/lNjNZqEMRaMTKZOSiqm+r7YL+PFDNV0f0fK7nRkhR4t+6Ly8JtmJZA94phHNMzqPhVdg=
  matrix:
  - TEST_CMD='sh hatchet.sh'
  - TEST_CMD="/tmp/testrunner/bin/run -c ."
